### ISSUE TITLE
基于最新版dc-sdk,dc-ui在vue事例工程中无法加载地图

### ISSUE THREAD

**Issue by AirWinger** [dvgis/dc-ui#3]
@cavencj 基于最新版dc-sdk,dc-ui在 [https://github.com/cavencj/dc-vue-app](vue事例工程) 无法加载地图,麻烦看下

**Comment by cavencj** [comment]
你好 我这边测试了 没有问题呢，可以正常加载呢

**Comment by AirWinger** [comment]
@cavencj 你好, 这边是通过在vue-app工程里引用下载下来的dc库来加载的,新版版的无法加载,老版本的可以,对js和vue不太熟,麻烦帮忙看下,谢谢
[dc-vue-app.zip](https://github.com/dvgis/dc-ui/files/7878561/dc-vue-app.zip), libs下的1.11版本是可以加载的,新版本的不能
